#!/usr/bin/env bash

set -Eeuo pipefail

fail() {
  printf 'Error: %s\n' "$1" >&2
  exit 1
}

log_step() {
  printf '\n==> %s\n' "$1"
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing required command: $1"
}

loaded_env_files=()

render_env_file() {
  bun --eval '
const { randomBytes } = require("node:crypto");

const source = await Bun.file("idp-client.yaml").text();
const config = Bun.YAML.parse(source);
const values = config.runtime_env?.values ?? {};
const generated = config.runtime_env?.generated ?? {};
const env = {};

function getPath(path) {
  return path.split(".").reduce((value, key) => value?.[key], config);
}

function resolveValue(value) {
  if (["string", "number", "boolean"].includes(typeof value)) {
    return String(value);
  }

  if (!value || typeof value !== "object") {
    throw new Error("Unsupported runtime_env value.");
  }

  if (value.from) {
    const resolved = getPath(value.from);

    if (Array.isArray(resolved)) {
      return resolved.join(value.join ?? " ");
    }

    if (resolved === undefined || resolved === null) {
      throw new Error(`Missing idp-client.yaml path: ${value.from}`);
    }

    return String(resolved);
  }

  throw new Error("Unsupported runtime_env object value.");
}

for (const [key, spec] of Object.entries(generated)) {
  if (spec?.from === "hydra_registration") {
    env[key] = "";
  } else if (spec?.type === "hex") {
    env[key] = randomBytes(Number(spec.bytes)).toString("hex");
  } else {
    env[key] = "";
  }
}

for (const [key, value] of Object.entries(values)) {
  env[key] = resolveValue(value);
}

function quote(value) {
  return `"${String(value)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, "\\\"")
    .replace(/\$/g, "\\$")
    .replace(/`/g, "\\`")}"`;
}

function commentsFor(key) {
  const spec = generated[key];

  if (spec?.from === "hydra_registration") {
    return [
      "# Fill after registering the hydra_client from idp-client.yaml in Hydra.",
      "# The platform orchestrator can generate this automatically.",
    ];
  }

  return [];
}

const preferredOrder = [
  "PORT",
  "HYDRA_ADMIN_URL",
  "HYDRA_PUBLIC_URL",
  "LOGIN_SERVER_CLIENT_ID",
  "LOGIN_SERVER_CLIENT_SECRET",
  "RESOURCE_SERVER_URL",
  "RESOURCE_SERVER_LOGIN_PATH",
  "RESOURCE_SERVER_IDENTIFIER_FIELD",
  "RESOURCE_SERVER_PASSWORD_FIELD",
  "RESOURCE_SERVER_AUDIENCE",
  "RESOURCE_SERVER_LOGIN_SCOPE",
  "LOGIN_REMEMBER_FOR_SECONDS",
  "CONSENT_REMEMBER_FOR_SECONDS",
];

const keys = [
  ...preferredOrder.filter((key) => key in env),
  ...Object.keys(env)
    .filter((key) => !preferredOrder.includes(key))
    .sort(),
];

const lines = [
  "# Generated by ./init.sh from idp-client.yaml.",
  "# This file is ignored by Git. Keep local credentials here only.",
  "",
];

for (const key of keys) {
  lines.push(...commentsFor(key));
  lines.push(`${key}=${quote(env[key])}`);
}

process.stdout.write(`${lines.join("\n")}\n`);
'
}

create_env_file_from_contract() {
  local env_file=".env.local"
  local tmp_file="${env_file}.tmp"

  [[ -f idp-client.yaml ]] || fail 'Missing idp-client.yaml. Cannot generate .env.local.'

  render_env_file >"${tmp_file}"
  chmod 600 "${tmp_file}"
  mv "${tmp_file}" "${env_file}"

  printf 'Created %s from idp-client.yaml.\n' "${env_file}"
  printf 'Fill LOGIN_SERVER_CLIENT_SECRET, then rerun ./init.sh.\n'
}

load_env_files() {
  local found=0
  local env_file

  for env_file in ../.env .env .env.local; do
    if [[ -f "$env_file" ]]; then
      loaded_env_files+=("$env_file")
      set -a
      # shellcheck disable=SC1090
      source "$env_file"
      set +a
      found=1
    fi
  done

  if ! ((found)); then
    create_env_file_from_contract
    exit 1
  fi
}

format_env_files() {
  local IFS=', '
  printf '%s' "${loaded_env_files[*]}"
}

require_env() {
  local missing=0
  local key

  for key in "$@"; do
    if [[ -z "${!key:-}" ]]; then
      printf 'Missing required environment variable: %s\n' "$key" >&2
      missing=1
    fi
  done

  ((missing == 0)) || fail 'Missing required login-server configuration.'
}

main() {
  require_command bun

  load_env_files
  log_step "Using env files: $(format_env_files)"

  export PORT="${PORT:-3002}"

  require_env \
    HYDRA_ADMIN_URL \
    HYDRA_PUBLIC_URL \
    LOGIN_SERVER_CLIENT_ID \
    LOGIN_SERVER_CLIENT_SECRET \
    RESOURCE_SERVER_URL \
    RESOURCE_SERVER_LOGIN_PATH \
    RESOURCE_SERVER_AUDIENCE \
    RESOURCE_SERVER_LOGIN_SCOPE

  log_step 'Installing dependencies'
  bun install

  log_step 'Running lint'
  bun run lint

  log_step 'Building application'
  bun run build

  log_step 'Starting development server'
  printf 'Login server: http://127.0.0.1:%s\n' "$PORT"
  exec bun run dev
}

main "$@"
